name: Heroku Deployment
on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.8.8
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        # Email that you use with heroku
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        # The appname to use for deploying/updating
        heroku_app_name: ${{secrets.HEROKU_APP}}
        # An optional buildpack to use when creating the heroku application
